### PR TITLE
Release the GIL, crosscat!!! 

### PR DESCRIPTION
**Pull request by alxempirical**
CrossCat wrapper to release the GIL

I don't care how grumpy a cat is, it shouldn't hold on to a thing like the GIL when it doesn't need to. I don't know how cats get away with this kind of stuff. We've been shaming dogs and each other about it for [millenia](https://en.wikipedia.org/wiki/The_Dog_in_the_Manger), but somehow when a cat does it it's supposed to be cute.

Options I considered:

- Releasing the gil in cython code, with `with nogil:`. This is cumbersome, because automatic translation between python and C++ `std` library data structures cannot take place in `with nogil:` blocks, so you have to litter the code with intermediate placeholder variables holding the translations.

- Simply putting `Py_BEGIN_ALLOW_THREADS` and `Py_END_ALLOW_THREADS` everywhere relevant in `State.cpp`. This makes the code non-reentrant, because [you can't nest calls to these macros](https://github.com/python/cpython/blob/master/Include/ceval.h#L158), and actually breaks crosscat already because crosscat calls some of its external API internally.

- [Adapting cython with a new keyword for this situation](https://groups.google.com/forum/#!topic/cython-users/q4j_Gf6HMeU).

- This way, which uses a specialized container class to wrap calls to the State object. This isn't as clean as adapting cython, but it allows for good separation of concerns (crosscat stays pure C++), and is hygenic in that modifications to the crosscat API can't have any functional impact unless the corresponding modifications are made to the wrapper API.

### CODE REVIEW

**Comment by gregory-marton** [comment]
Yes, it would be nice to allow threads in these thread-safe environments. Do you actually observe the expected performance benefit from releasing the global interpreter lock this way? Could you add that comparison to the discussion?

Is there a test that it would be relatively easy to write that might check that we retain that benefit through future changes?

**Comment by alxempirical** [comment]
There are places which would obviously benefit from thread-level parallelism such as [`simple_predictive_probability_multistate`](https://github.com/probcomp/crosscat/blob/0f25514184a55065fe329cf91ce425ff14154cc5/src/utils/sample_utils.py#L227), which iterates a time consuming calculation over the states.  I haven't included them in this PR, but I can include a few if you like.

**Comment by gregory-marton** [comment]
No, I understand the theoretical benefit. I'd like to confirm that we're actually getting that benefit in practice, at least on some machine at this time. If there is a repeatable automatic test associated, that would be even better, but perhaps not necessary.

**Comment by gregory-marton** [comment]
This could be as simple as using %time on an "ANALYZE ... FOR k ITERATIONS" call in an ipy notebook, attempting to hold other usage of the machine constant during the test period.

**Comment by alxempirical** [comment]
No problem.  I'll modify one of the functions which'll benefit and include a test demonstrating the speedup.

**Comment by alxempirical** [comment]
Hmm... maybe `ANALYZE` would Just Work.  I'll look into it.

**Comment by gregory-marton** [comment]
I can also imagine an automatic test of the flavor
```
fast_duration = time(do_parallelizable_thing())
with gil:
  slow_duration = time(do_parallelizable_thing())
assert slow_duration > 2 * fast_duration
```

**Comment by tibbetts** [comment]
Agree a quick automated test to make sure this doesn't regress in the future seems better than an integration test/demo with ANALYZE. Also to see the speedup doesn't the invocation have to come from two threads, which would increase the complexity of the test a bit beyond @gregory-marton's suggestion?

**Comment by alxempirical** [comment]
@tibbetts, you're right, but it should only increase the complexity a little.  There is an [`Executor.map`](https://docs.python.org/3/library/concurrent.futures.html#executor-objects) which has been [backported to python 2](https://github.com/agronholm/pythonfutures/blob/master/concurrent/futures/_base.py#L551).  Should be able to simply replace `LocalEngine.mapper` with that.

**Comment by riastradh-probcomp** [comment]
It seems to me the only place where it really makes sense to release the GIL is inside the p_State class's `transition` and `transition_`* methods, which mostly have no parameter conversions.

How bad is the `with nogil:` shortcoming -- does it silently cause data corruption in the multithreaded case, or does it fail noisily at run-time if parameter conversion happens while the GIL is released, or does the Cython compiler statically reject `with nogil:` if it surrounds any parameter conversions?

Any easy automatic test for this based on measuring timing requires the system testing it to have multiple idle cores, which is not reliable in general-purpose automatic tests.  Can you count the number of release/acquire cycles of the GIL instead?

**Comment by alxempirical** [comment]
Having trouble getting cython to cooperate right now, but here is the API I am thinking of adding to set up an automated test.  Comments welcome:  https://github.com/alxempirical/crosscat/commit/2e1e5acd30b9df58ffed1a2c1da219519a406346

`State.pyx` will `release_GIL=true` during module initialization, and provide a toggle function for it.   It can run a timed test with release_GIL on and off, and compare them.  I expect this test can be run in its own process, with a high cgroups [`cpu.shares` setting](http://askubuntu.com/questions/94619/how-to-set-cpu-limit-for-given-process-permanently-cpulimit-and-nice-dont-work) to ensure access to multiple CPUs..

**Comment by riastradh-probcomp** [comment]
I am very confused by your last commit and comment.  Does that C++ code even compile? Why are any changes to setup.py necessary, other than a one- or two-line change to switch to StateNoGIL.{pyx,cpp}?  Where does `release_GIL` get used?

As for cgroup configuration on Linux -- the fact that there is a certain way on a certain specific operating system to request scheduling in parallel (of which there are many, although I'm not sure `cpu.shares` has anything to do with parallelism) doesn't address the problem that you would be imposing a *physical* requirement on the machine running the automatic tests, or at least very funny faux-real-time clock shenanigans that I don't expect any existing operating system to do.

Can you address my question about `with nogil:` in Cython in <https://github.com/probcomp/crosscat/pull/94#issuecomment-214574694>?  I would rather avoid copypasta of an already too-complicated C++ API if possible.

**Comment by gregory-marton** [comment]
Re release-gil option: why not invoke State directly for the no-release case?

Re requirement of multiple cores in an automated test: Nice catch! I think it's fine to run a pre-test to check that multiprocessing in general runs faster than single processing, and simply pass if that is not the case.

Re static analysis, @riastradh-probcomp cython documents itself as not checking, letting you run the risk of memory corruption and other Bad Things. That sounds like the sort of behavior that is dangerous now, and not future-prone. Is that what you were asking?

**Comment by alxempirical** [comment]
> why not invoke State directly for the no-release case?

If there's a painless way to swap one out for the other, I would prefer that route.  I couldn't think of a way to do it without massive code duplication in `cdef extern from "StateNoGIL.h":`, `cdef extern from "State.h":`, and `cdef class p_State:`.  You could make StateNoGIL a subclass of State, rather than a container of it, or you could give `p_State` both a State `*thisptr` and a StateNoGIL `*thisptr`, and then decide on each function call, based on a flag, which one to call.  Or some more elegant way I haven't thought of.

**Comment by alxempirical** [comment]
> It seems to me the only place where it really makes sense to release the GIL is inside the p_State class's transition and transition_* methods, which mostly have no parameter conversions.

We're seeing long, choked `INITIALIZE <n> MODELS` calls when run on large data sets.  Same for `PROBABILITY` calls.  Basically the whole thing will benefit from thread-level parallelism.

**Comment by alxempirical** [comment]
> Where does release_GIL get used?

Here: https://github.com/alxempirical/crosscat/commit/2e1e5acd30b9df58ffed1a2c1da219519a406346#diff-8a5e980577c97f639c6a7c9b8188fc22R8

**Comment by riastradh-probcomp** [comment]
I meant to ask 'where does `release_GIL` get set?', not 'where does it get used?'.  That said, the line you quoted doesn't look like it's going to compile to me, unless there is some magic new development in C++11 that lets you omit parentheses around an `if` condition in certain circumstances but not others.

Also, I assume you've already tried using MultiprocessingEngine and found that it wasn't good enough?  Do you have any measurements to share?

**Comment by alxempirical** [comment]
`State.pyx` will set `release_GIL=true` during module initialization, and provide a toggle function for it.  I hadn't implemented that, yet.  It's a WIP commit.

There is no paralellization of `PROBABILITY` calculations using the `MultiprocessingEngine`.  Why `INITIALIZE` is getting choked is unclear, but it's the `PROBABILITY` calculations where it's hurting right now.

**Comment by riastradh-probcomp** [comment]
Have you tried using multiprocessing to parallelize the probability queries?  Maybe the communication bandwidth would be excessive, but I expect it to be a much simpler experiment to perform, and a safer avenue to pursue than multithreading.

**Comment by riastradh-probcomp** [comment]
By the way, evidently Cython does have some kind of static analysis to determine when releasing the GIL is safe -- see <http://docs.cython.org/src/quickstart/cythonize.html?highlight=gil> for details: running `cython -a` gives an HTML report that you can eyeball to check for white sections, which are safe for `with nogil:`.  This is not quite as automatic as one would hope from a compiler, but it's certainly better than nothing!

**Comment by alxempirical** [comment]
I've added a cython control to release the GIL, and combined with https://github.com/alxempirical/bayeslite/tree/generate-crosscat-prior-data will be able to generate representative data for this test.

**Pull request closed without merging**
