### PR TITLE
Really require cython for full builds

### PR DESCRIPTION
**Pull request by tibbetts**
If we are going to use Cython, don't try to recover when we can't import it, just fail, otherwise the later errors are confusing.

### CODE REVIEW

**Comment by riastradh-probcomp** [comment]
Date: Sat, 31 Oct 2015 14:56:32 -0700
   From: Richard Tibbetts <notifications@github.com>

   If we are going to use Cython, don't try to recover when we can't
   import it, just fail, otherwise the later errors are confusing.

This can't be right.  This means that you can't even use setup.py to
*discover* the dependency on Cython, listed in setup_requires.

I don't know off the top of my head what the right way to deal with
this is, but I'm sure there must be a standard way to deal with it.

**Comment by tibbetts** [comment]
The current setup.py doesn't correctly install cython, if you don't have cython installed (at least on OSX and I suspect elsewhere) it leads to confusing errors later in the build. I'll look at ways to do better.

**Comment by tibbetts** [comment]
The cython documentation at http://docs.cython.org/src/userguide/source_files_and_compilation.html doesn't mention this. The pattern crosscat was using seems to be based on http://stackoverflow.com/questions/4505747/how-should-i-structure-a-python-package-that-contains-cython-code and doesn't require cython after the sdist step, so a pip package doesn't have trouble. My change is that if sdist hasn't run, like we are building from git, then don't pretend we can get away without cython, just die. Improvements should be possible but will require additional dynamic loading cleverness beyond what we had.

**Comment by tibbetts** [comment]
Ok, improved this. It appears to me the build_ext cmdclass was actually not required. Now it works for me with or without cython preinstalled and installing from the result of sdist.

**Comment by riastradh-probcomp** [comment]
This breaks `python setup.py build` out of the Git repository -- nothing invokes Cython now, outside of the sdist command.

I'm looking into this to find a proper solution.

**Comment by riastradh-probcomp** [comment]
It appears that setup_requires is actually just a red herring here, and install_requires does everything we need in order to make `pip install .` work.

**Comment by tibbetts** [comment]
Fixed on a different branch

**Pull request closed without merging**
