### PR TITLE
Use print as a function.

### PR DESCRIPTION
**Pull request by madeleineth**
This is the first step to running under both Python 2 and 3.

### CODE REVIEW

**Comment by madeleineth** [comment]
FYI: Passes check.sh under Python 2.7.6 on Ubuntu 14.04.

**Comment by riastradh-probcomp** [comment]
One comment: why add the `from __future__ import print_function` annotations?  It appears that with the patch, every use of print would syntactically work as a statement and a function -- we don't ever pass it as an argument to another function, redirect output / apply it to multiple arguments, &c.

(It's not a problem -- I just find it to be visual clutter, particularly when most of those prints really have no business being prints at all instead of, e.g., asserts.)

**Comment by madeleineth** [comment]
Without the import, `print(a, b)` is equivalent to `print tuple([a, b])` in python2 but `print a, b` in python3.

FWIW, I tried not to judge whether the prints were a good idea.

**Comment by riastradh-probcomp** [comment]
Right, I see, OK.

**Pull request merged**
